//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevolvingFour.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RevolvingFourGame> RevolvingFourGames { get; set; }
    
        public virtual int uspCountAllGames(ObjectParameter retval)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspCountAllGames", retval);
        }
    
        public virtual ObjectResult<RevolvingFourGame> uspGetAllGames()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RevolvingFourGame>("uspGetAllGames");
        }
    
        public virtual ObjectResult<RevolvingFourGame> uspGetAllGames(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RevolvingFourGame>("uspGetAllGames", mergeOption);
        }
    }
}
