//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevolvingFour.Models
{
    using System;
    
    public partial class uspCountAllGames_Result1
    {
        public Nullable<int> retval { get; set; }
    }
}
